apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotplayground-deploy
  labels:
    app: iotplayground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotplayground
  template:
    metadata:
    sudo sed '/    server \/a     --flannel-iface "eth1"' /etc/systemd/system/k3s.service  labels:
        app: iotplayground
    spec:
      containers:
      - name: iotplayground
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
